/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-18-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Calculator2 {
    public static void welcomeMessage() {
        system.debug('Welcome to apex calc');
    }

    public static void printNewMessage(string msg){
        //msg = variable => used INSIDE the method.
        system.debug(msg);
    }
}
