/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-15-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Car99 {
    public void Car99() {
    //Public classes are accessible ONLY within the package. The public access modifier declares that this class is visible in your application or namespace.
    //Global classes are ACCESSIBLE outside of the package also.The global access modifier declares that this class is known by all Apex code everywhere.
    }
}