/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-15-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class GenericClass {
    public void callCalc() {
        Calculator c2 = new Calculator();
        integer c2sum33 = c2.add(10,15,25);
        system.debug('Generic Class is '+ callCalc);
    }
}
